apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysbench-client
  labels:
    name: sysbench-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sysbench-client
  template:
    metadata:
      labels:
        name: sysbench-client
    spec:
      containers:
      - name: sysbench-client
        image: satchpx/sysbench-client:1.0.0
        imagePullPolicy: Always
        command: [ "/opt/bin/run" ]